# ~/.config/helix/config.toml
theme = "beans"
[editor]
line-number = "relative"
[keys.normal."space".c]
s = ":! $HOME/csan.sh %{buffer_name} ; echo done"
t = ":! $HOME/test.sh %{buffer_name}"
h = ":! printf \"%{selection}\" | $HOME/hash.sh"

# ~/.config/helix/languages.toml
indent = {tab-width = 4, unit = " "}
